version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: creditguard-ai:latest
    container_name: creditguard_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
