name: Docker Image Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker Build
        uses: docker/build-push-action@v5
        with:
          context: ./5_Project_Development_Phase
          file: ./5_Project_Development_Phase/Dockerfile
          push: false
          tags: credit-card-approval-prediction:latest
